package com.example.aaron.greendaoexample.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PHONE_LIST".
 */
public class PhoneList {

    private Long id;
    /** Not-null value. */
    private String phone;
    private long userId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhoneList() {
    }

    public PhoneList(Long id) {
        this.id = id;
    }

    public PhoneList(Long id, String phone, long userId) {
        this.id = id;
        this.phone = phone;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
